"""percentage model

Revision ID: 1f0ef482644b
Revises: f635b435dfdd
Create Date: 2025-10-01 13:49:08.366436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f0ef482644b'
down_revision = 'f635b435dfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('percentage_container_movements')
    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('voyages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('berth_loc', sa.String(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('voyages_port_id_fkey'), type_='foreignkey')
        batch_op.drop_column('port_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('port_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('voyages_port_id_fkey'), 'ports', ['port_id'], ['id'])
        batch_op.drop_column('berth_loc')

    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    op.create_table('percentage_container_movements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cm_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bongkaran_pengajuan_empty_20dc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bongkaran_pengajuan_full_20dc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bongkaran_pengajuan_empty_40hc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bongkaran_pengajuan_full_40hc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pengajuan_acc_empty_20dc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pengajuan_acc_full_20dc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pengajuan_acc_empty_40hc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pengajuan_acc_full_40hc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('acc_tlss_empty_20dc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('acc_tlss_full_20dc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('acc_tlss_empty_40hc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('acc_tlss_full_40hc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('acc_turun_cy_empty_20dc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('acc_turun_cy_full_20dc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('acc_turun_cy_empty_40hc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('acc_turun_cy_full_40hc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_bongkaran_20dc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_bongkaran_40hc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_pengajuan_20dc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_pengajuan_40hc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_acc_20dc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_acc_40hc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tlss_20dc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tlss_40hc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_turun_20dc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_turun_40hc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('percentage_pengajuan_20dc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('percentage_pengajuan_40hc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('percentage_acc_20dc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('percentage_acc_40hc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('percentage_tl_20dc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('percentage_tl_40hc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('percentage_realisasi_20dc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('percentage_realisasi_40hc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cm_id'], ['container_movements.id'], name=op.f('percentage_container_movements_cm_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('percentage_container_movements_pkey')),
    sa.UniqueConstraint('cm_id', name=op.f('percentage_container_movements_cm_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
