"""percentage model 2

Revision ID: 394c15b3d5fb
Revises: 1f0ef482644b
Create Date: 2025-10-01 13:49:45.434097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '394c15b3d5fb'
down_revision = '1f0ef482644b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('percentage_container_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cm_id', sa.Integer(), nullable=False),
    sa.Column('bongkaran_pengajuan_empty_20dc', sa.Float(), nullable=True),
    sa.Column('bongkaran_pengajuan_full_20dc', sa.Float(), nullable=True),
    sa.Column('bongkaran_pengajuan_empty_40hc', sa.Float(), nullable=True),
    sa.Column('bongkaran_pengajuan_full_40hc', sa.Float(), nullable=True),
    sa.Column('pengajuan_acc_empty_20dc', sa.Float(), nullable=True),
    sa.Column('pengajuan_acc_full_20dc', sa.Float(), nullable=True),
    sa.Column('pengajuan_acc_empty_40hc', sa.Float(), nullable=True),
    sa.Column('pengajuan_acc_full_40hc', sa.Float(), nullable=True),
    sa.Column('acc_tlss_empty_20dc', sa.Float(), nullable=True),
    sa.Column('acc_tlss_full_20dc', sa.Float(), nullable=True),
    sa.Column('acc_tlss_empty_40hc', sa.Float(), nullable=True),
    sa.Column('acc_tlss_full_40hc', sa.Float(), nullable=True),
    sa.Column('acc_turun_cy_empty_20dc', sa.Float(), nullable=True),
    sa.Column('acc_turun_cy_full_20dc', sa.Float(), nullable=True),
    sa.Column('acc_turun_cy_empty_40hc', sa.Float(), nullable=True),
    sa.Column('acc_turun_cy_full_40hc', sa.Float(), nullable=True),
    sa.Column('total_bongkaran_20dc', sa.Integer(), nullable=True),
    sa.Column('total_bongkaran_40hc', sa.Integer(), nullable=True),
    sa.Column('total_pengajuan_20dc', sa.Integer(), nullable=True),
    sa.Column('total_pengajuan_40hc', sa.Integer(), nullable=True),
    sa.Column('total_acc_20dc', sa.Integer(), nullable=True),
    sa.Column('total_acc_40hc', sa.Integer(), nullable=True),
    sa.Column('total_tlss_20dc', sa.Integer(), nullable=True),
    sa.Column('total_tlss_40hc', sa.Integer(), nullable=True),
    sa.Column('total_turun_20dc', sa.Integer(), nullable=True),
    sa.Column('total_turun_40hc', sa.Integer(), nullable=True),
    sa.Column('percentage_pengajuan_20dc', sa.Float(), nullable=True),
    sa.Column('percentage_pengajuan_40hc', sa.Float(), nullable=True),
    sa.Column('percentage_acc_20dc', sa.Float(), nullable=True),
    sa.Column('percentage_acc_40hc', sa.Float(), nullable=True),
    sa.Column('percentage_tl_20dc', sa.Float(), nullable=True),
    sa.Column('percentage_tl_40hc', sa.Float(), nullable=True),
    sa.Column('percentage_realisasi_20dc', sa.Float(), nullable=True),
    sa.Column('percentage_realisasi_40hc', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cm_id'], ['container_movements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cm_id')
    )
    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('voyages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('port_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'ports', ['port_id'], ['id'])
        batch_op.drop_column('berth_loc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('berth_loc', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('port_id')

    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    op.drop_table('percentage_container_movements')
    # ### end Alembic commands ###
