"""vessel, voyage, containermovement models

Revision ID: 74da2dfa1978
Revises: b30008b78eca
Create Date: 2025-09-16 08:44:36.264903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74da2dfa1978'
down_revision = 'b30008b78eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voyages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('voyage_no', sa.String(length=50), nullable=False),
    sa.Column('voyage_yr', sa.Integer(), nullable=False),
    sa.Column('berth_loc', sa.String(length=100), nullable=True),
    sa.Column('date_berth', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('container_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voyage_id', sa.Integer(), nullable=False),
    sa.Column('bongkaran_empty_20dc', sa.Integer(), nullable=True),
    sa.Column('bongkaran_empty_40hc', sa.Integer(), nullable=True),
    sa.Column('bongkaran_full_20dc', sa.Integer(), nullable=True),
    sa.Column('bongkaran_full_40hc', sa.Integer(), nullable=True),
    sa.Column('pengajuan_empty_20dc', sa.Integer(), nullable=True),
    sa.Column('pengajuan_empty_40hc', sa.Integer(), nullable=True),
    sa.Column('pengajuan_full_20dc', sa.Integer(), nullable=True),
    sa.Column('pengajuan_full_40hc', sa.Integer(), nullable=True),
    sa.Column('acc_pengajuan_empty_20dc', sa.Integer(), nullable=True),
    sa.Column('acc_pengajuan_empty_40hc', sa.Integer(), nullable=True),
    sa.Column('acc_pengajuan_full_20dc', sa.Integer(), nullable=True),
    sa.Column('acc_pengajuan_full_40hc', sa.Integer(), nullable=True),
    sa.Column('total_pengajuan_20dc', sa.Integer(), nullable=True),
    sa.Column('total_pengajuan_40hc', sa.Integer(), nullable=True),
    sa.Column('teus_pengajuan', sa.Integer(), nullable=True),
    sa.Column('realisasi_mxd_20dc', sa.Integer(), nullable=True),
    sa.Column('realisasi_mxd_40hc', sa.Integer(), nullable=True),
    sa.Column('realisasi_fxd_20dc', sa.Integer(), nullable=True),
    sa.Column('realisasi_fxd_40hc', sa.Integer(), nullable=True),
    sa.Column('shipside_yes_mxd_20dc', sa.Integer(), nullable=True),
    sa.Column('shipside_yes_mxd_40hc', sa.Integer(), nullable=True),
    sa.Column('shipside_yes_fxd_20dc', sa.Integer(), nullable=True),
    sa.Column('shipside_yes_fxd_40hc', sa.Integer(), nullable=True),
    sa.Column('shipside_no_mxd_20dc', sa.Integer(), nullable=True),
    sa.Column('shipside_no_mxd_40hc', sa.Integer(), nullable=True),
    sa.Column('shipside_no_fxd_20dc', sa.Integer(), nullable=True),
    sa.Column('shipside_no_fxd_40hc', sa.Integer(), nullable=True),
    sa.Column('total_realisasi_20dc', sa.Integer(), nullable=True),
    sa.Column('total_realisasi_40hc', sa.Integer(), nullable=True),
    sa.Column('teus_realisasi', sa.Integer(), nullable=True),
    sa.Column('turun_cy_20dc', sa.Integer(), nullable=True),
    sa.Column('turun_cy_40hc', sa.Integer(), nullable=True),
    sa.Column('teus_turun_cy', sa.Integer(), nullable=True),
    sa.Column('percentage_vessel', sa.Float(), nullable=True),
    sa.Column('obstacles', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voyage_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('container_movements')
    op.drop_table('voyages')
    op.drop_table('vessels')
    # ### end Alembic commands ###
