"""cost rate model

Revision ID: d8af99aad7d4
Revises: 394c15b3d5fb
Create Date: 2025-10-04 10:38:21.684112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8af99aad7d4'
down_revision = '394c15b3d5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('tdk_tl_20mt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tdk_tl_40mt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tdk_tl_20fl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tdk_tl_40fl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tl_20mt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tl_40mt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tl_20fl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tl_40fl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipside_yes_20mt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipside_yes_40mt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipside_yes_20fl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipside_yes_40fl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipside_no_20mt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipside_no_40mt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipside_no_20fl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipside_no_40fl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('turun_cy_20mt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('turun_cy_40mt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('turun_cy_20fl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('turun_cy_40fl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voyage_cost_estimations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voyage_id', sa.Integer(), nullable=False),
    sa.Column('estimation_cost1', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estimation_cost2', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('final_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voyage_cost_estimations')
    op.drop_table('cost_rates')
    # ### end Alembic commands ###
